remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-them
title: [ECUGEN Workshop KDD 2022]
description: [Content understanding and generation for ecommerce workshop at KDD 2022]
show_downloads: [false]
